# name: CI
# on:
#   pull_request:
#     branches:
#       - master
#   push:
#     branches:
#       - master

# jobs:
#   cloudflare_pages:
#     name: run peanut to build the app
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#       - uses: actions/setup-java@v1
#         with:
#           java-version: "12.x"
#       - uses: subosito/flutter-action@v1
#         with:
#           channel: "stable"
#       - run: git config --global user.email "mightynawaf@gmail.com"
#       - run: git config --global user.name "MightyNawaf"
#       - run: flutter pub global activate peanut
#       - run: flutter pub get
#       - run: git push origin --delete gh-pages
#       - run: flutter build web
#       - run: flutter pub global run peanut
#       - run: git push origin --set-upstream gh-pages
name: Flutter Web CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      my_secret: ${{secrets.GH_DEPLOY}}
    steps:
    - uses: actions/checkout@v1
    - uses: subosito/flutter-action@v1
      with:
        channel: beta
    - run: flutter config --enable-web
    - run: flutter pub get
#     - run: flutter test
    - run: flutter build web
    - name: Archive Production Artifact
      uses: actions/upload-artifact@master
      with:
        name: web-build
        path: build/web
    - name: Download Artifact
      uses: actions/download-artifact@master
      with:
        name: web-build 
    - name: Display structure of build files
      run: ls -R
      working-directory: ./web
    - name: Deploy to GH Pages
      run: |
        cd build/web
        git init
        # type configurations: your user.email and user.name followed lines 
        # git config --global user.email your_email 
        # git config --global user.name your_name 
        git config --global user.email mightynawaf@gmail.com
        git config --global user.name MightyNawaf
        git status
        # change this remote url for examle your remote url is https://github.com/onatcipli/flutter_web.git then the following:
        git remote add origin https://mightynawaf:U7y6t5r4e3w2q\@GITHUB@github.com/MightyNawaf/cicd.git
        git checkout -b gh-pages
        git add --all
        git commit -m "update"
        git push origin gh-pages -f