name: Flutter Web CI
on:
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      my_secret: ${{secrets.GH_DEPLOY}}
    steps:
    - uses: actions/checkout@v1
    - uses: subosito/flutter-action@v1
      with:
        channel: beta
    # Added this
    - name: Bulding web version
      run: |
        cd apps/khotta
        flutter config --enable-web
        flutter pub get
        flutter build web
    - name: Updating khotta-test branch
      run: |
        cd apps/khotta/build/web
        git init
        git config --global user.email mightynawaf@gmail.com
        git config --global user.name MightyNawaf
        git status
        git remote add origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
        git checkout -b khotta-test
        git add --all
        git commit -m "update"
        git push origin khotta-test -f