name: Flutter Web CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    steps:
    - uses: actions/checkout@v3
    - uses: subosito/flutter-action@v1
      with:
        channel: stable
    # Added this
    - name: Bulding web version
      run: |
        cd apps/khotta
        flutter config --enable-web
        flutter pub get
        flutter build web
    - name: Publish
      uses: cloudflare/pages-action@1
      with:
        apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        projectName: cicd
        directory: apps/khotta/build/web
        gitHubToken: ${{ secrets.GITHUB_TOKEN }}